services:
  db:
    image: postgres:16
    container_name: fieldflow_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.3.0-management
    container_name: fieldflow_rabbitmq
    env_file:
      - ../.env
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../codigo/Back
    container_name: fieldflow_api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ../codigo/Back
    container_name: fieldflow_worker
    command: ["python", "-m", "worker"]
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
